version: '3'

services:
  db:
    restart: always
    image: "postgres:alpine"
  redis:
    restart: always
    image: "redis:alpine"
    ports:
      - 6379
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
  backend:
    restart: always
    build: ./backend
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code
    working_dir: /code
    links:
      - db:db
      - redis:redis
    depends_on:
      - db
      - redis
  backendtest:
    restart: always
    build: ./backend
    command: watchmedo auto-restart --recursive --pattern="*.py" --directory="." python3 manage.py test
    volumes:
      - ./backend:/code
    working_dir: /code
    links:
      - db:db
      - redis:redis
    depends_on:
      - db
      - redis
  frontend:
    restart: always
    build: ./frontend
    volumes:
      - ./frontend:/app
    working_dir: /app
    entrypoint: sh entrypoint.sh
    links:
      - backend
  nginx:
    image: "nginx:1.14-alpine"
    links:
      - backend
      - frontend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '8080:80'
