# Generated by Django 2.1.4 on 2019-01-08 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_basegamepiece'),
    ]

    operations = [
        migrations.AddField(
            model_name='basegamepiece',
            name='has_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='basegamepiece',
            name='number_of_items',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='basegamepiece',
            name='order',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='basegamepiece',
            name='shape',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='game.GamePieceShape'),
        ),
        migrations.AddField(
            model_name='gamepieceorientation',
            name='order',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gamepieceorientation',
            name='down',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gamepieceorientation',
            name='left',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gamepieceorientation',
            name='right',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gamepieceorientation',
            name='up',
            field=models.BooleanField(default=False),
        ),
    ]
