# Generated by Django 2.1.4 on 2019-01-09 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20190108_0816'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CollectableItems',
            new_name='CollectableItem',
        ),
    ]
