# Generated by Django 2.1.4 on 2019-01-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20190109_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='basegamepiece',
            name='title',
            field=models.CharField(default='title', max_length=255),
            preserve_default=False,
        ),
    ]
