# Generated by Django 2.1.4 on 2019-01-11 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20190111_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamepiece',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='game.Game'),
        ),
    ]
