# Generated by Django 2.1.4 on 2019-01-18 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_auto_20190111_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usercounter',
            name='game_piece',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.GamePiece'),
        ),
    ]
