# Generated by Django 2.1.4 on 2019-04-05 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_usercounter_starting_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercounter',
            name='starting_game_piece',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='startcounters', to='game.GamePiece'),
        ),
        migrations.AlterField(
            model_name='usercounter',
            name='game_piece',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currentcounters', to='game.GamePiece'),
        ),
    ]
