# Generated by Django 2.1.4 on 2019-04-05 10:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0017_auto_20190405_0954'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserCounter',
            new_name='Player',
        ),
    ]
