# Generated by Django 2.1.4 on 2019-04-05 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_playercollectableitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='collectable_items',
        ),
    ]
