# Generated by Django 2.1.4 on 2019-04-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_remove_player_collectable_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
