# Generated by Django 2.1.8 on 2019-05-03 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0024_auto_20190503_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='completed_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='game_piece',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currentcounters', to='game.GamePiece'),
        ),
        migrations.AlterField(
            model_name='player',
            name='starting_game_piece',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='startcounters', to='game.GamePiece'),
        ),
        migrations.AlterField(
            model_name='player',
            name='starting_position',
            field=models.IntegerField(blank=True, choices=[(1, 'top_left'), (7, 'top_right'), (43, 'bottom_left'), (49, 'bottom_right')], null=True),
        ),
    ]
