# Generated by Django 2.1.8 on 2019-05-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0025_auto_20190503_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
