# Generated by Django 2.1.8 on 2019-05-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0026_auto_20190503_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='turn_status',
            field=models.IntegerField(choices=[(1, 'Pre-insert of spare square'), (2, 'Post-insert of spare square')], default=1),
        ),
    ]
