# Generated by Django 2.1.8 on 2019-05-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0027_player_turn_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='spare_square_last_inserted_at',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='spare_square_last_inserted_into',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
