# Generated by Django 2.1.8 on 2019-05-09 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0028_auto_20190508_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerTurn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_status', models.IntegerField(choices=[(1, 'Pre-insert of spare square'), (2, 'Post-insert of spare square')], default=1)),
                ('spare_square_inserted_into', models.CharField(blank=True, max_length=255, null=True)),
                ('spare_square_inserted_at', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='spare_square_last_inserted_at',
        ),
        migrations.RemoveField(
            model_name='game',
            name='spare_square_last_inserted_into',
        ),
        migrations.RemoveField(
            model_name='player',
            name='turn_status',
        ),
        migrations.AddField(
            model_name='playerturn',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Player'),
        ),
    ]
