# Generated by Django 2.2.13 on 2020-06-16 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0029_auto_20190509_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playercollectableitem',
            name='collectable_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='playercollectableitem', to='game.CollectableItem'),
        ),
    ]
